within Tutorial;
model Foam232EndCapSweep
    .VaporCycle.Experiments.HydrogenStorage.TankSizing.Tanks.CryogenicFoam foam232(layer1(E = 0.7),insulationSizing = .VaporCycle.Experiments.HydrogenStorage.TankSizing.Tanks.Utilities.InsulationSizing.Dormancy,r_outer_par = 4.67 / (2),massHydAvail_prscr = 13620,sizingParametrization = .VaporCycle.Experiments.HydrogenStorage.TankSizing.Tanks.Utilities.sizingParametrization.MassAndRadius,p_filling = 165.5e3,volumeFractionVapor = 0.13,p_max = 404e3,sf = 2.2,layer2(redeclare replaceable record ThermalMaterial = .Modelon.Thermal.MaterialProperties.PropertyData.ConstantProperties.PolyurethaneFoamHuete),redeclare replaceable package StartSection = .VaporCycle.Experiments.HydrogenStorage.TankSizing.Tanks.Utilities.TopLevelReplaceableGeometry.Hemispheroidal,redeclare replaceable package EndSection = .VaporCycle.Experiments.HydrogenStorage.TankSizing.Tanks.Utilities.TopLevelReplaceableGeometry.Hemispheroidal,s_ratio_StartSection = s_ratio,s_ratio_EndSection = s_ratio) annotation(Placement(transformation(extent = {{-40,8},{-20,28}},origin = {0,0},rotation = 0)));
    .Modelica.Thermal.HeatTransfer.Sources.FixedTemperature fixedTemperature(T = 288.15) annotation(Placement(transformation(extent = {{-90,16},{-70,36}},origin = {0,0},rotation = 0)));
    parameter Real s_ratio = 1 "ratio between r_inner and the principal semi-axis for hemispheroidal end caps";
equation
    connect(fixedTemperature.port,foam232.port_amb) annotation(Line(points = {{-70,26},{-30.200000000000003,26},{-30.200000000000003,27.8}},color = {191,0,0}));
    annotation(Icon(coordinateSystem(preserveAspectRatio = false,extent = {{-100.0,-100.0},{100.0,100.0}}),graphics = {Rectangle(lineColor={0,0,0},fillColor={230,230,230},fillPattern=FillPattern.Solid,extent={{-100.0,-100.0},{100.0,100.0}}),Text(lineColor={0,0,255},extent={{-150,150},{150,110}},textString="%name")}));
end Foam232EndCapSweep;
